version: "3"

services:
  terminusdb-server:
    image: terminusdb/terminusdb-server:latest
    container_name: terminusdb-server
    pull_policy: always
    hostname: terminusdb-server
    tty: true
    ports:
      - 6364:6363
    env_file: .env
    environment:
      - TERMINUSDB_SERVER_PORT=6363
      # DISABLE THESE ENV VARIABLES WHEN RUNNING TERMINUSDB IN PRODUCTION
      # OR PUT AN AUTHENTICATION GATEWAY IN FRONT OF TERMINUSDB
      - TERMINUSDB_INSECURE_USER_HEADER=X-User-Forward
      - TERMINUSDB_INSECURE_USER_HEADER_ENABLED=true
    volumes:
      # For the use of a local dashboard
      #      - ./dashboard:/app/terminusdb/dashboard
      - ./storage:/app/terminusdb/storage
  vectorlink:
    image: terminusdb/vectorlink:v0.0.8
    env_file: .env
    environment:
      - TERMINUSDB_CONTENT_ENDPOINT=http://terminusdb-server:6363/api/index
      - TERMINUSDB_USER_FORWARD_HEADER=X-User-Forward
    volumes:
      - ./vector_storage:/app/storage
    command: ["./terminusdb-semantic-indexer", "serve", "--directory", "/app/storage"]
  change-request-api:
    image: terminusdb/terminusdb-change-request-api:v0.0.9
    restart: always
    env_file: .env
    ports:
      - 6363:3035
    environment:
      - SERVER_ENDPOINT=http://terminusdb-server:6363
      - USE_CHANGE_REQUEST=${USE_CHANGE_REQUEST:-true}
      # Add your OpenAI key in a .env file
      - OPENAI_SERVER_URL=http://vectorlink:8080

      # There are multiple ways to configure TerminusDB security through
      # environment variables. Several reasonable options are included below.
      # Uncomment the option you decide on and comment out others.
      # Don't forget to change the default password!

      # TerminusDB should be set up behind a TLS-terminating reverse
      # proxy with admin authentication provided by password.
      # - TERMINUSDB_ADMIN_PASS=root  #  Change before exposing to the internet.

      # The storage path of terminusdb databases is /app/terminusdb/storage in case
      # you want to persist storage somewhere else.
