version: "3"

volumes:
  terminusdb_storage:

services:
  terminusdb-server:
    image: terminusdb/terminusdb-server:latest
    container_name: terminusdb-server
    hostname: terminusdb-server
    tty: true
    ports:
      - 6363:6363
    environment:
      - TERMINUSDB_SERVER_PORT=6363

      # There are multiple ways to configure TerminusDB security through
      # environment variables. Several reasonable options are included below.
      # Uncomment the option you decide on and comment out others.
      # Don't forget to change the default password!

      # TerminusDB should be set up behind a TLS-terminating reverse
      # proxy with admin authentication provided by password.
      # - TERMINUSDB_ADMIN_PASS=root  #  Change before exposing to the internet.

      # The storage path of terminusdb databases is /app/terminusdb/storage in case
      # you want to persist storage somewhere else.
