[package]
name = "terminusdb-community"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swipl = "0.3.6"
lcs = "0.2.0"
terminusdb-store-prolog = {path="../terminusdb-store-prolog"}
