# Build and run tests every night on non-Docker systems.
name: ARM64 docker build

on:
  schedule:
    - cron:  '45 2 * * *'
  workflow_dispatch:
  push:
  workflow_call:

jobs:
  arm64_docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: terminusdb
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: terminusdb/terminusdb-server:experimental-arm64-build
          push: true
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TERMINUSDB_GIT_HASH=${{ github.sha }}
            CARGO_NET_GIT_FETCH_WITH_CLI=true
