name: Benchmark

on:
  workflow_call:

env:
  NODE_VERSION: '16'

jobs:

  benchmark:
    name: Run
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: terminusdb-server-docker-image

      - name: Run server
        run: |
          docker load < terminusdb-server-docker-image.tar.gz
          docker run \
            --detach \
            --net=host \
            terminusdb/terminusdb-server:local

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v2

      - name: Run benchmarks
        working-directory: tests
        run: |
          mkdir -p results/js_benchmark_results
          npm ci
          node bench.js --json > "results/js_benchmark_results/${GITHUB_SHA}.json"


      - name: Add SSH Key
        run: |
          mkdir -p ${HOME}/.ssh
          echo "Created SSH DIR"
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ${HOME}/.ssh/known_hosts
          echo "Add known hosts"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${HOME}/.ssh/github_actions
          echo "Add SSH private key"
          chmod 600 ${HOME}/.ssh/github_actions
          echo "Change SSH permissions"
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "Started ssh agent"
          ssh-add ${HOME}/.ssh/github_actions
          echo "Add SSH key"

      - name: Make k6 benchmark dir
        working-directory: tests
        run: mkdir -p results/k6_benchmark_results


      - name: Run k6 benchmark
        working-directory: tests
        run: |
          ssh "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" "benchmark $GITHUB_SHA" > "results/k6_benchmark_results/${GITHUB_SHA}.json"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tests/results/
          keep_files: true

