name: Benchmark

on:
  push:
    # We only use the `main` branch, because the benchmark graphs are linear.
    # The results are confusing when commits from different branches are
    # interleaved.
    branches:
      - main
    # Don't run if only the docs are changed.
    paths-ignore:
      - 'docs/**'

jobs:
  benchmark:
    concurrency: benchmark
    runs-on: ubuntu-latest
    if: github.repository_owner == 'terminusdb'
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Check out terminusdb-http-perf
        uses: actions/checkout@v2
        with:
          repository: terminusdb-labs/terminusdb-http-perf
          path: terminusdb-http-perf

      - name: Add SSH Key
        run: |
          mkdir -p ${HOME}/.ssh
          ssh-keyscan "${{ secrets.SSH_HOST }}" >> ${HOME}/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${HOME}/.ssh/github_actions
          chmod 600 ${HOME}/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ${HOME}/.ssh/github_actions


      - name: Run benchmark
        run: |
          ssh "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" "benchmark $GITHUB_SHA" > data-points.json

      - name: Transform results
        run: ./terminusdb-http-perf/metrics.sh data-points.json > results.json

      - name: Store results
        uses: terminusdb-labs/benchmark-tracker@beta
        with:
          tool: generic
          output-file-path: results.json
          benchmark-data-dir-path: benchmark
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
