name: Benchmark

on:
  push:
    # We only use the `main` branch, because the benchmark graphs are linear.
    # The results are confusing when commits from different branches are
    # interleaved.
    branches:
      - main
    # Don't run if only the docs are changed.
    paths-ignore:
      - 'docs/**'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Check out terminusdb-http-perf
        uses: actions/checkout@v2
        with:
          repository: terminusdb-labs/terminusdb-http-perf
          path: terminusdb-http-perf

      - name: Install k6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6
          k6 version

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag terminusdb/terminusdb-server:local

      - name: Run server
        run: docker run --detach --name terminusdb -p 6363:6363 terminusdb/terminusdb-server:local

      - name: Run benchmark
        run: k6 run --no-summary --no-usage-report --iterations 10 --out json=data-points.json terminusdb-http-perf/response/all.js

      - name: Transform results
        run: ./terminusdb-http-perf/metrics.sh data-points.json > results.json

      - name: Store results
        uses: terminusdb-labs/benchmark-tracker@beta
        with:
          tool: generic
          output-file-path: results.json
          benchmark-data-dir-path: benchmark
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
