name: CI

on:
  push:
    branches:
    tags:
    paths-ignore:
      - 'docs/**'
      - LICENSE
      - README.md
  pull_request:
    # Don't run if only the docs are changed.
    paths-ignore:
      - 'docs/**'
      - LICENSE
      - README.md
  workflow_dispatch:

env:
  TERMINUSDB_DOCKER_IMAGE_NAME: terminusdb/terminusdb-server
  TERMINUSDB_DOCKER_IMAGE_TAG: terminusdb/terminusdb-server:local
  TERMINUSDB_STORE_PROLOG_VERSION: v0.19.7
  TUS_VERSION: v0.0.5
  SWIPL_LINTER_VERSION: v0.7
  NODE_VERSION: '16'

jobs:

  # Check if this job is already running with the same or newer content.
  #
  # This should never skip push events: they are used by begin_deploy.
  check_skip:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ github.repository }}"
