name: Docs

on:
  push:
    paths:
      - '**.md'
      - 'docs/**'
      - LICENSE
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'
      - LICENSE

jobs:

  # This is required for status checks.
  all_checks_pass:
    name: All checks pass
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to be checked! 😌"
