name: Docs
on:
  push:
    branches:
      - main
      - rc
      - canary
    tags:
      - v* # Environment variables available to all jobs and steps in this workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Copy readme over
        run: sed 's,docs/,,' README.md > docs/README.md

      - name: Extract branch name
        shell: bash
        run: |
            echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch


      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs/
          target-folder: ${{ steps.extract_branch.outputs.branch }}
          clean-exclude: dev/bench
