# Build and run tests every night of the working week.
#
# These mainly exist to test installing TerminusDB on different systems.
name: Nightly

on:
  schedule:
    - cron:  '45 1 * * MON-FRI'
  workflow_dispatch:

jobs:

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install swi-prolog
        run: |
          # Installing swipl on Debian: https://www.swi-prolog.org/build/PPA.html
          sudo apt-add-repository ppa:swi-prolog/stable
          sudo apt-get update
          sudo apt-get install swi-prolog

      - name: Check out tus
        uses: actions/checkout@v2
        with:
          repository: terminusdb/tus
          path: tus
          ref: v0.0.5

      - name: Install tus
        run: swipl -g "pack_install('file://$GITHUB_WORKSPACE/tus', [interactive(false)])"

      - name: Install terminus_store_prolog
        run: swipl -g "pack_install(terminus_store_prolog, [interactive(false), upgrade(true)])"

      - run: make

      - run: ./terminusdb test

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install swi-prolog
        run: |
          # Installing swipl on macOS: https://www.swi-prolog.org/build/macos.html
          brew install swi-prolog

      - name: Check out tus
        uses: actions/checkout@v2
        with:
          repository: terminusdb/tus
          path: tus
          ref: v0.0.5

      - name: Install tus
        run: swipl -g "pack_install('file://$GITHUB_WORKSPACE/tus', [interactive(false)])"

      - name: Install terminus_store_prolog
        run: swipl -g "pack_install(terminus_store_prolog, [interactive(false), upgrade(true)])"

      - run: make

        # This can take a long time to run (12 - 20 minutes).
      - run: ./terminusdb test
