# Build and run tests after every push and pull request
name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  check_skip:
    runs-on: ubuntu-latest

    outputs:
      should_skip: ${{ steps.check_skip.outputs.should_skip }}

    steps:
      - uses: fkirc/skip-duplicate-actions@master
        id: check_skip

  ubuntu:
    runs-on: ubuntu-latest

    # Run if not already run (e.g. with a push followed by a PR)
    if: ${{ needs.check_skip.outputs.should_skip != 'true' }}

    steps:
      - uses: actions/checkout@v2

      - name: Install swi-prolog
        run: |
          # Installing swipl on Debian: https://www.swi-prolog.org/build/PPA.html
          sudo apt-add-repository ppa:swi-prolog/stable
          sudo apt-get update
          sudo apt-get install swi-prolog

      - name: Check out tus
        uses: actions/checkout@v2
        with:
          repository: terminusdb/tus
          path: tus
          ref: v0.0.5

      - name: Install tus
        run: swipl -g "pack_install('file://$GITHUB_WORKSPACE/tus', [interactive(false)])"

      - name: Install terminus_store_prolog
        run: swipl -g "pack_install(terminus_store_prolog, [interactive(false), upgrade(true)])"

      - run: make

      - run: ./terminusdb test
